kind: pipeline
name: telegram-front

steps:
  - name: install
    image: node:14
    commands:
      - npm install

  - name: build
    image: node:14
    commands:
      - npm run build

  - name: deploy
    image: ubuntu:20.04
    environment:
      SSH_KEY:
        from_secret: SSH_KEY
      SSH_USER:
        from_secret: SSH_USER
      SSH_HOST:
        from_secret: SSH_HOST
      SSH_PATH:
        from_secret: SSH_PATH
      SSH_PASS:
        from_secret: SSH_PASS
    commands:
      - apt-get update && apt-get install -y openssh-client sshpass
      - mkdir -p ~/.ssh
      - echo "$SSH_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - sshpass -p $SSH_PASS scp -r build/* $SSH_USER@$SSH_HOST:$SSH_PATH
  # - name: deploy
  #   image: appleboy/drone-ssh:1.6.2
  #   settings:
  #     host:
  #       from_secret: SSH_HOST
  #     username:
  #       from_secret: SSH_USER
  #     # key:
  #     #   from_secret: SSH_KEY
  #     password:
  #       from_secret: SSH_PASS
  #     port: 22
  #     target:
  #       from_secret: SSH_PATH
  #     source: build/
  #     script:
  #       - sudo rm -rf $SSH_PATH/*
  #       - sudo cp -R build/* $SSH_PATH
