kind: pipeline
name: telegram-front

steps:
  - name: install
    image: node:14
    commands:
      - npm install

  - name: build
    image: node:14
    commands:
      - npm run build

  - name: deploy
    image: ubuntu:20.04
    commands:
      - apt-get update && apt-get install -y openssh-client
      - mkdir -p ~/.ssh
      - echo "servername 8.8.8.8" > /etc/resolv.conf
      - echo "$SSH_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - cat ~/.ssh/id_rsa
      - scp -r build/* telegramshop@193.36.85.250:$SSH_PATH
  # - name: deploy
  #   image: appleboy/drone-ssh:1.6.2
  #   settings:
  #     host:
  #       from_secret: SSH_HOST
  #     username:
  #       from_secret: SSH_USER
  #     # key:
  #     #   from_secret: SSH_KEY
  #     password:
  #       from_secret: SSH_PASS
  #     port: 22
  #     target:
  #       from_secret: SSH_PATH
  #     source: build/
  #     script:
  #       - sudo rm -rf $SSH_PATH/*
  #       - sudo cp -R build/* $SSH_PATH
